from enum import Enum


class Event(str, Enum):
    NEW_CANDLE = "NEW_CANDLE"
    INDICATORS_UPDATED = "INDICATORS_UPDATED"
    MARKET_UPDATED = "MARKET_UPDATED"
    SIGNAL_CREATED = "SIGNAL_CREATED"
    TRADE_APPROVED = "TRADE_APPROVED"
    ORDER_EXECUTED = "ORDER_EXECUTED"
    POSITION_CLOSED = "POSITION_CLOSED"